CarRent/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRent.Data.Repo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarRent.Controllers
{
    public class AdminController : Controller
    {
        private ILocationRepo repo;

        public AdminController(ILocationRepo _repo)
        {
            repo = _repo;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult LocationIndex(int locationId)
        {
            return View(
               repo.GetAll()
                .Include(a => a.Address)
               .FirstOrDefault(l => l.Location_ID == locationId));
        }
    }
}

CarRent/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using CarRent.Data.Repo;
using CarRent.Models.ViewModel;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using CarRent.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Threading.Tasks;

namespace CarRent.Controllers
{
    public class CarController : Controller
    {
        private readonly IHostingEnvironment environment;
        private ICarRepo repository;
        private IGradeRepo repoGrade;
        public int PageSize = 12;

        public CarController(ICarRepo _repo, IGradeRepo _repograde, IHostingEnvironment _environment)
        {
            repository = _repo;
            repoGrade = _repograde;
            environment = _environment;
        }

        public ViewResult CarsList(string category, int carPage = 1)
            => View(new CarListView
            {
                Cars = repository.getCarByGrade(repository.GetAll(),  category)
                        .Include(c => c.Grade)
                        .OrderBy(p => p.Car_ID)
                        .Skip((carPage - 1) * PageSize)
                        .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = carPage,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                        repository.GetAll().Count() :
                        repository.getCarByGrade(repository.GetAll(), category).Count()
                },
                CurrentCategory = category
            });

        public IActionResult Car(int carId)
            => View(repository.GetAll().Include(g=>g.Grade).FirstOrDefault(p=>p.Car_ID==carId));
       
        public ViewResult CarsListAdmin(string category, int carPage = 1)
             => View(new CarListView
                {
                    Cars = repository.getCarByGrade(repository.GetAll(), category)
                        .Include(c => c.Grade)
                        .OrderByDescending(p => p.Car_ID)
                        .Skip((carPage - 1) * PageSize)
                        .Take(PageSize),
                    PagingInfo = new PagingInfo
                    {
                        CurrentPage = carPage,
                        ItemsPerPage = PageSize,
                        TotalItems = category == null ?
                        repository.GetAll().Count() :
                        repository.GetAll().Where(p => p.Grade.GradeType.ToString() == category).Count()
                    },
                    CurrentCategory = category
                });
       
        public ViewResult Edit(int carID) =>
            View(new EditCarView
            {
                Car=repository.GetAll()
                .FirstOrDefault(p => p.Car_ID == carID),
                GradeList=repoGrade.GetAll().Distinct().ToList()
            });

        public ViewResult Create() => View("Edit", 
            new EditCarView
            {
                Car=new Car(),
                GradeList= repoGrade.GetAll().Distinct().ToList()
            });

        [HttpPost]
        public async Task<IActionResult> Edit(Car car, IFormFile pic)
        {
            if (ModelState.IsValid)
            {
                if (pic != null)
                {
                    int carID;
                    if (car.Car_ID == 0) { carID = repository.GetAll().Count() + 1; }
                    else { carID = car.Car_ID; }
                    string uploadPath = Path.Combine(environment.WebRootPath, "uploads");
                    Directory.CreateDirectory(Path.Combine(uploadPath, carID.ToString()));

                    string filename = pic.FileName;
                    if (filename.Contains('\\'))
                    {
                        filename = filename.Split('\\').Last();
                    }
                    using (FileStream fs = new FileStream(Path.Combine(uploadPath, carID.ToString(), filename), FileMode.Create))
                    {
                        await pic.CopyToAsync(fs);
                    }
                    car.Img = filename;
                }
                repository.Save(car);
                    TempData["message"] = $"Zapisano zmiany.";
                    return RedirectToAction("CarsListAdmin");
            }
            else
            {
                return View(new EditCarView
                {
                    Car = car,
                    GradeList = repoGrade.GetAll().Distinct().ToList()
                });
            }
        }
    }
}

CarRent/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarRent</title>
    <link href="https://fonts.googleapis.com/css?family=Lato:300i,400|Oswald:300,400,700&amp;subset=latin-ext" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="~/lib/jquery/jquery-3.3.1.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <environment include="Development">
        <link rel="stylesheet" href="~/css/css_style/style.css" />
    </environment>
</head>
<body>
    <!--Header-->
    <div class="bg-primary my-header">
        <div class="container">
            <ul class="nav flex-column flex-md-row justify-content-lg-end text-uppercase">
                <li class="nav-item my-header-item-active">
                    <a class="nav-link my-header-item-link" asp-area="" asp-controller="Home" asp-action="Index">Strona główna</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white my-header-item-link" asp-area="" asp-controller="Home" asp-action="About">O Nas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white my-header-item-link" asp-area="" asp-controller="Car" asp-action="CarsList">Oferta</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white my-header-item-link" asp-area="" asp-controller="Location" asp-action="LocationList">Kontakt</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white my-header-item-link" asp-area="" asp-controller="Admin" asp-action="Index">Panel sterowania</a>
                </li>
                <li>
                    @await Html.PartialAsync("_LoginPartial")
                </li>
            </ul>
        </div>
    </div>

    <div>
        @RenderBody()
    </div>

    <div class="my-footer-top">
        <div class="container my-footer-top-content">
            <div class="row">
                <div class="col-md-4 offset-md-2 mb-5">
                    <h4 class="text-uppercase text-white mb-3">O projekcie</h4>
                    <p class="my-footer-text my-footer-p">
                        Praca wykonana w ramach zaliczenia studiów podyplomowych „PROGRAMOWANIE NA PLATFORMIE .NET”.<br />
                        <span class="text-primary font-weight-bold">Instytut Podstaw Informatyki Polskiej Akademii Nauk 2018 rok</span>
                    </p>
                </div>
                <div class="col-md-3 col-md-offset-2 mb-5">
                    <h4 class="text-uppercase text-white mb-3">Kontakt</h4>
                    <ul class="list-unstyled my-footer-text my-footer-contact-list">
                        <li class="my-footer-contact-item">
                            <span class="mr-2"><img src="~/img/ui/user-avatar.png" /></span>
                            Piotr Soja
                        </li>
                        <li class="my-footer-contact-item">
                            <span class="mr-2"><img src="~/img/ui/contact-footer-icon-email.png" /></span>
                            piotrsoja@o2.pl
                        </li>
                    </ul>
                </div>
                <div class="col-md-3 mb-5">
                    <h4 class="text-uppercase text-white mb-3">Nawigacja</h4>
                    <ul class="list-unstyled">
                        <li>
                            <a class="my-footer-text" href="#">Strona główna</a>
                        </li>
                        <li>
                            <a class="my-footer-text" href="#">Logowanie na konto</a>
                        </li>
                        <li>
                            <a class="my-footer-text" href="#">Rejestracja</a>
                        </li>
                        <li>
                            <a class="my-footer-text" href="#">Oferta</a>
                        </li>
                        <li>
                            <a class="my-footer-text" href="#">O Nas</a>
                        </li>
                        <li>
                            <a class="my-footer-text" href="#">Kontakt</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>