CarRent/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarRent.Models
{
    public class Customer:Person
    {
        public virtual ICollection<Order> Orders { get; set; } = new HashSet<Order>();
        public virtual ICollection<UserRating> UserRatings { get; set; } = new HashSet<UserRating>();
    }
}

CarRent/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarRent.Data.Repo;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarRent.Controllers
{
    public class CustomerController : Controller
    {
        private ICustomerRepo repo;
        public CustomerController(ICustomerRepo _repo)
        {
            repo = _repo;
        }

        public ViewResult CustomerList()
             => View(
                 repo.GetAll()
                 .OrderBy(l => l.LastName)
                 .Include(a => a.ApplicationUser)
                 .Include(a => a.Address)
                 );

        public IActionResult Customer(int customerID)
            => View(repo.GetAll()
                .Include(a => a.ApplicationUser)
                .Include(a => a.Address)
                .FirstOrDefault(p => p.Person_ID == customerID));
    }
}

CarRent/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CarRent.Data.Repo;
using CarRent.Models.ViewModel;
using Microsoft.EntityFrameworkCore;
using CarRent.Models;

namespace CarRent.Controllers
{
    public class OrderController : Controller
    {
        private IOrderRepo repository;
        private ICarDetalistRepo repositoryCarDetal;
        public int PageSize = 12;

        public OrderController(IOrderRepo _repo, ICarDetalistRepo _repositoryCarDetal)
        {
            repository = _repo;
            repositoryCarDetal = _repositoryCarDetal;
        }

        public ViewResult OrderList(int carPage = 1)
        => View(new OrderListView
        {
            Orders = repository.GetAll()
                    .Include(c => c.Customer)
                    .Include(c=>c.Car)
                    .OrderBy(p => p.DateEnd)
                    .Skip((carPage - 1) * PageSize)
                    .Take(PageSize),
            PagingInfo = new PagingInfo
            {
                CurrentPage = carPage,
                ItemsPerPage = PageSize,
                TotalItems = repository.GetAll().Count()
            },
        });

        public ViewResult OrderListByLocation(string location, int carPage = 1)
        {
            return View(new OrderListView
            {
                Orders = repository.GetAll()
                    .Where(l => l.LocationEnd == location)
                    .Include(c => c.Customer)
                    .Include(c => c.Car)
                    .OrderBy(p => p.DateEnd)
                    .Skip((carPage - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = carPage,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.GetAll().Count()
                }
            });
        }
        public ViewResult OrderHistory(int customerID, int carPage = 1)
        {
            return View(new OrderListView
            {
                Orders = repository.GetAll()
                    .Where(l => l.Customer.Person_ID == customerID)
                    .Include(c => c.Customer)
                    .Include(c => c.Car)
                    .OrderBy(p => p.DateEnd)
                    .Skip((carPage - 1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = carPage,
                    ItemsPerPage = PageSize,
                    TotalItems = repository.GetAll().Count()
                }
            });
        }
        public IActionResult Order(int orderId, string registerNumber)
           => View(new OrderView()
           {
               Order = repository.GetAll()
               .Include(c => c.Customer)
               .Include(c => c.Car)
               .Include(c => c.Car.Grade)
               .FirstOrDefault(c => c.Order_ID == orderId),

               CarDetails= repositoryCarDetal.GetAll()
               .Include(c=>c.Location.Address)
               .Where(x => x.RegistrationNumber == registerNumber).FirstOrDefault()
               
           });
        public ViewResult EditState(int orderId) =>
             View(
                repository.GetAll()
                 .Include(c => c.Customer)
                 .Include(c => c.Car)
                .FirstOrDefault(l => l.Order_ID == orderId));
        [HttpPost]
        public IActionResult EditState(Order order)
        {
            if (ModelState.IsValid)
            {
                repository.EditState(order);
                TempData["message"] = $"Zapisano zmiany.";
                return RedirectToAction("OrderList");
            }
            else
            {
                return View(order);
            }
        }
    }
}

CarRent/Views/Customer/Customer.cshtml
@model Customer
@{
    ViewData["Title"] = "Employee";
}

<div class="container mt-4" style="margin-bottom: 10%">
    <div class="row">
        <div class="col-md-10">
            <h2>@Model.Name @Model.LastName</h2>
            <div class="my-hr my-page-intro-rule"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            PESEL:
        </div>
        <div class="col-md-6 text-primary">
            @Model.PESEL
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            Adres zamieszkania:
        </div>
        <div class="col-md-6 text-primary">
            @Model.Address.City @Model.Address.PostalCode @Model.Address.Street @Model.Address.Number
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            Numer telefonu:
        </div>
        <div class="col-md-6 text-primary">
            @Model.ApplicationUser.PhoneNumber
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            Adres e-mail:
        </div>
        <div class="col-md-6 text-primary">
            @Model.ApplicationUser.Email
        </div>
    </div>
</div>

CarRent/Views/Customer/CustomerList.cshtml
@model IEnumerable<Customer>

@if (TempData["message"] != null)
{
    <div class="alert alert-success">@TempData["message"]</div>

}
<div class="container mt-4 mb-5">
    <h2 class="text-uppercase">Wszyscy <span class="text-primary">klienci</span></h2>
    <div class="my-hr my-page-intro-rule"></div>
    <table class="table table-striped table-bordered">
        <tr>
            <th>Nazwisko i Imię</th>
            <th>Adres</th>
            <th>PESEL</th>
            <th class="text-center">Akcje</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.LastName @item.Name</td>
                <td>@item.Address.City @item.Address.PostalCode @item.Address.Street @item.Address.Number</td>
                <td>@item.PESEL</td>
                <td class="text-center">
                    <a asp-action="Customer" class="btn btn-sm btn-info mt-2 mb-2"
                       asp-route-customerID="@item.Person_ID">INFO</a>
                    <a asp-controller="Order" asp-action="OrderHistory" class="btn btn-sm btn-info mt-2 mb-2"
                       asp-route-customerID="@item.Person_ID">HISTORIA</a>
                </td>
            </tr>

        }
    </table>
</div>